"""add recordings

Revision ID: 9c7540dbdfa9
Revises: 
Create Date: 2018-10-09 11:04:16.164939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c7540dbdfa9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entry_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recordings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.Text(), nullable=False),
    sa.Column('path', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lang', sa.String(length=2), nullable=False),
    sa.Column('word', sa.Text(), nullable=False),
    sa.Column('entry_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['entry_type_id'], ['entry_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('examples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('example', sa.Text(), nullable=False),
    sa.Column('translation', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('translation', sa.Text(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['entry_id'], ['entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('verb_tenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time_reference', sa.Text(), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('first_singular', sa.Text(), nullable=False),
    sa.Column('second_singular', sa.Text(), nullable=False),
    sa.Column('third_singular', sa.Text(), nullable=False),
    sa.Column('first_plural', sa.Text(), nullable=False),
    sa.Column('second_plural', sa.Text(), nullable=False),
    sa.Column('third_plural', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('verb_tenses')
    op.drop_table('translations')
    op.drop_table('examples')
    op.drop_table('entries')
    op.drop_table('recordings')
    op.drop_table('entry_types')
    # ### end Alembic commands ###
